version: "3"

services:
  homepage:
    image: reservation/nginx:v3
    ports:
      - 9595:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 1
        window: 120s
